### ISSUE TITLE
target.json can be changed

### ISSUE THREAD

**Issue by zesterer** [rust-console/gba#112]
I've been doing some experimenting and I've realised that using `llvm-target: arm7-none-agb` with `features: [thumb-mode]` seems to work as an alternative to using `llvm-target: thumbv4-none-agb`. Am I right in thinking that this change should allow the compiler to interleave regular ARM and thumb instructions?

**Comment by Lokathor** [comment]
the compiler can already do that. the thumb target is essentially an alias for an arm target with thumb mode by default for all functions.

**Comment by zesterer** [comment]
Fair enough, that's nice to know.
