### ISSUE TITLE
Add a .text_fast section to IWRAM to allow users to more easily speed up hot code

### ISSUE THREAD

**Issue by zesterer** [rust-console/gba#113]
Code executing from IWRAM is *significantly* faster than code executed from ROM. Adding a section in the linker and advice in the book about adding `#[link_section = ".text_fast"]` to hot functions is likely to help a lot of users achieve better performance.

**Comment by Lokathor** [comment]
We probably want to call it `.iwram`, because that's the more commonly used name for it, but yeah this is a good idea.

@zesterer you should do the PR when you have the time :3

**Comment by Lokathor** [comment]
https://github.com/rust-console/gba/pull/118 fixed this
