### ISSUE TITLE
Crate doesn't compile anymore using the Makefile.toml

### ISSUE THREAD

**Issue by Sp00ph** [rust-console/gba#117]
When running the following commands:
```shell
git clone https://github.com/rust-console/gba --depth=1
cd gba
cargo make
```
with the newest version of `cargo-make` and rust 1.52.0 nightly, I get the following error message:
```
error: couldn't allocate output register for constraint '{r14}'
   --> src\sync\statics.rs:122:8
    |
122 |       "ldmia {0}!, {{r2-r5,r8-r10,r12,r14}}",
    |        ^
```
This happens both with the msvc and with the gnu toolchain.

**Comment by Lokathor** [comment]
oops, i guess we goofed on the CI somewhere. I'll try to have a look soon.

**Comment by Lokathor** [comment]
I haven't had a chance to sit down at my own computer yet, but i see that the CI here has passed in just the past few hours: https://github.com/rust-console/gba/pull/118

Can you double check that you're on the latest Nightly and try again? Sometimes Nightly has temporary issues like this.

**Comment by Sp00ph** [comment]
Doing a `rustup update` fixed it :)
