### ISSUE TITLE
i think the irq and test_savegame examples are broken in 0.4

### ISSUE THREAD

**Issue by Lokathor** [rust-console/gba#129]
they certainly draw stuff on the screen and do... *something*, but it's not immediately obvious that they're drawing useful stuff. I could have easily broken something in the update.

**Comment by Lymia** [comment]
`test_savegame` seems fine. Check the mgba debug output.

**Comment by Lymia** [comment]
`test_savegame` seems to be working fine according to the mgba debug output. However, something's clearly not right with the rendering. It's supposed to start with a yellow screen that slowly fills with green, but it's instead black filling red.

**Comment by Lymia** [comment]
You have a typo here. This should be `b << 10 | g << 5 | r`.

https://github.com/rust-console/gba/blob/main/src/mmio_types/color.rs#L17

**Comment by Lokathor** [comment]
well that would be one critical error.

**Comment by Lokathor** [comment]
Got this solved.
