### ISSUE TITLE
Recommend TOML-formatted rust-toolchain

### ISSUE THREAD

**Issue by crawfxrd** [rust-console/gba#139]
Since rustup 1.23.0, a TOML format can be used for toolchain files. The advantage of  this is that it allows specifying required components.

Then, simply by running `cargo build`, the correct toolchain (nightly) and required components (`rust-src`) will automatically be installed.

(rustup 1.24.0 adds support for a `.toml` extension, which _should_ be used for a TOML-formatted toolchain file. But the GitHub runners are not yet updated to have it, requiring user intervention for Actions (ref: https://github.com/crawfxrd/gba-dev-rs/commit/4901f91b780cea82fd6f4e649129c4afd18b3328).)

**Comment by Lokathor** [comment]
Tim with any more advice like this I might end up with a respectable repository some day.

**Comment by crawfxrd** [comment]
Haha, same. I'm not sure I will be updating my repo anytime soon, though (problems with `grit` killed my interest for what I want to do next). But these 2 changes are too good not to push here.
