### ISSUE TITLE
`SOUNDCNT_L`/`SOUNDCNT_H` definitions are missing

### ISSUE THREAD

**Issue by Lymia** [rust-console/gba#143]

**Comment by Lokathor** [comment]
They're under alternate names, https://github.com/rust-console/gba/blob/main/src/mmio_addresses.rs#L129-L162, but the doc comments should help people find the correct thing if they do a search in the docs (except docs.rs was broken at the time so the docs aren't on docs.rs, but you could build them locally)

**Comment by Lymia** [comment]
The individual channels are present, but the master volume control registers are not.

https://mgba-emu.github.io/gbatek/#--gba-sound-control-registers

I can't find any references to `0x0400_0080` in the codebase, for example.

**Comment by Lokathor** [comment]
ohhhh, okay you're right.
