### ISSUE TITLE
how to handle multi-mode addresses?

### ISSUE THREAD

**Issue by Lokathor** [rust-console/gba#148]
Some addresses have some read-only bits as well as some read-write bits. Eg: the sound handling has an address with read-only bits for if sound is playing, as well as a read-write bit for enabling the sound system.

Do we want to just let these be kinda "mixed" read-only and read-write?

Alternately, we could have two VolAddress constants, one which uses a type to expose the read-only info and one which uses a type to expose the read-write info.

A complication is the equality impls of the types involved. If people expect PartialEq and Eq to work on only the bits that are actually exposed by a given type, then each version of a newtype that only uses some of the bits would need to mask out the other bits during an equality test. Then again, equality tests are (i think) likely to be rare, so maybe that's fine.

Ultimately people *can* go around our abstractions without much fuss, so it doesn't have to be perfect. We're aiming for "good default" with this one.

**Comment by LunarLambda** [comment]
Dunno if this has been solved, but I would just treat the register as R/W but use an mmio_type that only has getters for the read-only bits

Read-only bits should just be included in equality, i.e. a display status in vblank is different from a display status not in vblank.

This *would* mean you can't construct a Display status value that has the in-vblank bit set, but it would be trivial to add something like From<u16>, and just mask off the unused bits (or TryFrom for registers where this could cause invalid bit patterns, such as DisplayControl's mode field or DMAControl's address controls)

**Comment by Lokathor** [comment]
I think we'll just give full getters/setters to each field and the document which fields are read only when you actually write the value to mmio.
