### ISSUE TITLE
`asm!` and `global_asm!` moved to `core::arch`

### ISSUE THREAD

**Issue by mattlgy** [rust-console/gba#156]
https://github.com/rust-lang/stdarch/pull/1183 moved the asm macros the `core::arch` namespace. Currently, things don't compile with a recent nightly. Using a nightly from before the move works as a workaround.

**Comment by mattlgy** [comment]
This seems like a pretty easy fix. Planning to add the `using` statements to the relevant files today/tomorrow, but figured I would open an issue first.

**Comment by Lokathor** [comment]
Ah yeah, i saw the stabilization report but forgot that the macro moved.
