### ISSUE TITLE
[Suggestion] Make voladdress and bitfrob workplace inherited

### ISSUE THREAD

**Issue by gruxor** [rust-console/gba#173]
Not a huge deal, but if the plan is to use them as argument types for certain functions (u8x2, etc.) the types should most likely be included without needing to manually add the package containing those types. Alternatively, the types could be wrapped or re-implemented, I suppose. 

There's probably a bunch of other options for making it a bit cleaner if none of the above seems enticing.

**Comment by Lokathor** [comment]
they could be publicly re-exported from the `gba::prelude`, that's probably the simplest fix.
