### ISSUE TITLE
License header for linker_scripts/mono_boot.ld?

### ISSUE THREAD

**Issue by jturcotte** [rust-console/gba#183]
I'm guessing from the documentation that I'm supposed to copy https://github.com/rust-console/gba/blob/main/linker_scripts/mono_boot.ld into my own project so that the cargo config's rustflags can refer to it. I would however prefer the license of that file to be clear if I'm copying it.

I can see `license = "Zlib OR Apache-2.0 OR MIT"` in your Cargo.toml, but I'm not sure what I would have to put as the copyright holder anyway.

So I'm wondering if you could put some license header specifically in that file, or have some other idea how to deal with this.
Thanks

**Comment by Lokathor** [comment]
Ah, very good point that having to copy the linker script itself out of this repo into another can present confusion.

In https://github.com/rust-console/gba/commit/8bb1d42634dcd3e21896f2cf35ff3f090f224c4d I added a line at the top saying that the linker script specifically will just be CC0 public domain, for maximum simplicity. I've also explained this in the changelog for 0.11.1.

**Comment by jturcotte** [comment]
That's awesome, thanks.
