### ISSUE TITLE
Can't link with `static mut`s

### ISSUE THREAD

**Issue by eevee** [rust-console/gba#46]
Trying to compile a program containing a (non-elided) `static mut` produces some delightful linker spew:

```
  = note: arm-none-eabi-ld: warning: cannot find entry symbol __start; defaulting to 0000000008000000
          `.bss._ZN16fox_flux_advance4test17h9ec3708eaa2e7c78E' referenced in section `.text._ZN16fox_flux_advance4step17hd2b45f0f3bd89611E' of /home/eevee/dev/fox-flux-advance.git/target/thumbv4-none-agb/debug/deps/fox_flux_advance-3341f37616403a6a.3y0pnfisrximx3xe.rcgu.o: defined
 in discarded section `.bss._ZN16fox_flux_advance4test17h9ec3708eaa2e7c78E' of /home/eevee/dev/fox-flux-advance.git/target/thumbv4-none-agb/debug/deps/fox_flux_advance-3341f37616403a6a.3y0pnfisrximx3xe.rcgu.o
```

Linkers aren't my area, but the problem seems to be that globals go in `.bss` sections, and those are dropped by the linker script.  Adding this fixed it for me:

```
    .bss : {
        *(.bss .bss.*);
        . = ALIGN(4);
    } >iwram = 0xff
```

No idea if `iwram` is appropriate or not.  Please let me know if not.  ;)

**Comment by Lokathor** [comment]
Officially, `static mut` is so dangerous that they want to [remove it from the language](https://github.com/rust-lang/rust/issues/53639) in a future edition.

So, we _will_ fix this, but you're still discouraged from ever using `static mut` in the strongest possible terms.

@ketsuban you're the keeper of the linker script, perhaps EWRAM might be better? Or the base of IWRAM with a symbol generated for "end of static mut" so you know where the safe lower bound of IWRAM is within rust? Or, even if it's in EWRAM, we probably want such marker symbol.

**Comment by eevee** [comment]
In my defense, I was _planning_ on replacing it with some kind of Cell.  Really.  Eventually.

Look, it's embedded, everything's unsafe anyway—

**Comment by Lokathor** [comment]
;3c
