### ISSUE TITLE
Have a way to flush MGBADebug / clear the buffer

### ISSUE THREAD

**Issue by hyarsan** [rust-console/gba#51]

**Comment by Lokathor** [comment]
Near as I can tell, every time you send a message the buffer is automatically cleared by the emulator.

**Comment by hyarsan** [comment]
This is probably a problem of the libretro port of mGBA. My apologies.

**Comment by Lokathor** [comment]
No problem! I should put this information into the documentation for later.

**Comment by hyarsan** [comment]
alright!

**Comment by Lokathor** [comment]
Fixed, will go out in 0.3.1
