### ISSUE TITLE
Randomization

### ISSUE THREAD

**Issue by Lokathor** [rust-console/gba#56]
* Some form of PRNG that's optimized to the GBA
* Picking random values in a range and such too
* Basically we should take [randomize](https://github.com/Lokathor/randomize-rs) and make sure it works super well on the GBA and then use that.

**Comment by Hpmason** [comment]
I forked your randomize repo, and tried implemented 32->32 bit PCG-RXS-M-XS. You can find it [here](https://github.com/Hpmason/randomize). I think I implemented it correctly and I made 2 ROMs comparing the original Pcg32, which uses 64bit state and inc to produce u32, and it's about 6x faster to use the 32 bit state and inc.

I'd like to see if this can be merged with the gba crate and how best to do that. Also is there anything else I'd be able to strip down/change to make it run better on the GBA?

**Comment by Lokathor** [comment]
I think that we want to make like a `gba::random` module or something to put a bunch of prng stuff in.

Probably we want two prng impls: one for 32-bit output and one for 16-bit output. I don't think that 8-bit output would be any faster or better quality than just the 16-bit outputs, but I think that 16-bit output can probably be faster than 32-bit outputs, and if you just want the prng for like rolling 1d6 you don't need 32-bit.
