### ISSUE TITLE
Convert C test roms to Rust

### ISSUE THREAD

**Issue by Lokathor** [rust-console/gba#75]
There is a set of C test roms: https://github.com/mgba-emu/suite

We can use them as part of a usability and coverage test. Basically we want to write the C test rom in Rust as rustily as possible, and then make sure the crate supports thay code well, ideally with zero unsafe needed in the test rom code.

**Comment by redruin1** [comment]
Is this issue still active? If so, do you have any restrictions on what such a suite should look like? I'm thinking about making a translation to explore the API a little bit, but I would like to conform to the design principles already set out in this crate, if there are any.

**Comment by Lokathor** [comment]
This entire crate is largely not active.

For contributing to Rust on GBA your best bet is likely the `agb` crate.

https://github.com/agbrs/agb

**Comment by redruin1** [comment]
Gotcha, thanks for the heads up!
