### ISSUE TITLE
Inline more

### ISSUE THREAD

**Issue by hyarsan** [rust-console/gba#86]
A lot of functions / methods aren't inlined with `#[inline]` when it might be beneficial to do so. For example I think it's good to inline the `new` method when using the `newtype` macro.

**Comment by Lokathor** [comment]
Good point. I'd accept PRs in this area if you have any immediate concerns, though I generally just build the whole game with LTO which you could also try for now.

**Comment by Lokathor** [comment]
Status: we should add guidance in the README that people should really be using LTO in their GBA roms if they want maximum performance (which you do with only 16Mhz)
