### ISSUE TITLE
Using signum() in draw_line

### ISSUE THREAD

**Issue by xTibor** [rust-console/gba#89]
There's this pattern in the `draw_line()` functions:

```rust
let mut dx1 = 0;
...
if w < 0 {
  dx1 = -1;
} else if w > 0 {
  dx1 = 1;
};
```

It's rather verbose and there's a function on top of primitives that calculates this, `signum()`. Using that these patterns would shorten to a single line, for example: `let dx1 = w.signum();`.

Are there any technical reason why that function is not used here?

https://doc.rust-lang.org/std/primitive.isize.html#method.signum

**Comment by Lokathor** [comment]
Nope, just that way because it was translated very literally from C.

I haven't worked on this repo much lately, but I'd accept a PR. Most of my recent GBA work has been tinkering with assembly to improve my familiarity there.

**Comment by Lokathor** [comment]
The current version of the crate last lost its draw_line function because the bitmap modes aren't particularly the best in the first place. I'm gonna close this issue.
