### ISSUE TITLE
Recent Rust nightlies may not put crt0.o at the beginning of the file

### ISSUE THREAD

**Issue by ketsuban** [rust-console/gba#90]
I recently updated my nightly and discovered that my `crt0` code was being put last in the binary's `.text` output section rather than first, which is a problem when that contains the ROM header which needs to be at `0x8000000`. My guess is something changed internally in Rust, but whatever. The solution I came across was the `STARTUP` linker script command; it lets you supply a single object file which is included first.

Unfortunately this is a barrier to adopting LLD, since it doesn't understand the `STARTUP` command.

**Comment by Lokathor** [comment]
Dag.

Well, when you post to rustc about this be sure to link here so that it shows up as a note I guess. Maybe it was just some accident that can be fixed up easily.

**Comment by ketsuban** [comment]
Some digging around leads me to suspect this isn't actionable on Rust's part since the order of input sections was never defined. That said, we can absolutely file a bug on LLD for not supporting `STARTUP` since (as I understand it) it's supposed to be a drop-in replacement for GNU linkers.

**Comment by ketsuban** [comment]
I was digging around [the implementation of targets](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/mod.rs) and found that if I add this to the target file...
```json
    "pre-link-args-crt": {
        "ld": [
            "crt0.o"
        ]
    },
```
...then the `crt0.o` file is linked first.

**Comment by Lokathor** [comment]
I put that into the `master` branch as well, but I didn't pull and test it I guess.
