### ISSUE TITLE
Incorrect behavior on Mode4::write

### ISSUE THREAD

**Issue by Sp00ph** [rust-console/gba#98]
In the `Mode4::write` method, the parity of the x coordinate is handled incorrectly. It writes to the low byte when in reality it should write to the high byte, and vice versa.

When doing the following:
```rust
// ... setup code
for i in 0..160 {
    Mode4::write(Page::Zero, i, i, 0) // with appropriate palette setup
}
```
you don't get the expected single line, but instead two parallel dotted lines.

This can trivially be fixed by changing
```rust 
if real_index == rounded_down_index
```
in line 212 of `src/vram/bitmap.rs` to
```rust 
if real_index != rounded_down_index
```

**Comment by Lokathor** [comment]
sounds good. wanna do the PR?
